spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password:
      label: master
server:
  port: 8769